##
## Authentication processes
##

auth_allow_cleartext = no

auth_mechanisms = plain login 

passdb_default_password_scheme = BLF-CRYPT

##
## Password and user databases
##

!include auth-sql.conf.ext
