##
## Mailbox locations and namespaces
##

mail_home = /var/vmail/%{user | domain}/%{user | username}
mail_driver = maildir
mail_path = /var/vmail/%{user | domain}/%{user | username}
mailbox_list_layout = fs

# If you need to set multiple mailbox locations or want to change default
# namespace settings, you can do it by defining namespace sections.
namespace inbox {
  inbox = yes

  # See 15-mailboxes.conf for definitions of special mailboxes.
}

mail_uid = vmail
mail_gid = vmail

mail_privileged_group = vmail


