##
## Settings for the Sieve interpreter
##

sieve_script global_before {
  type = before
  path = /var/vmail/sieve/global/spam-global.sieve
}

# Personal user Sieve scripts and the active link path
sieve_script personal {
  type = personal
  path = /var/vmail/sieve/%{user | domain}/%{user | username}/scripts
  active_path = /var/vmail/sieve/%{user | domain}/%{user | username}/active-script.sieve
}

quota "User quota" {
  driver = maildir
  exceeded_message = User %{user | username} has exhausted allowed storage space.
}
