## Dovecot configuration file

dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

# Enable installed protocols
protocols = imap lmtp
!include_try /usr/share/dovecot/protocols.d/*.protocol

sql_driver = mysql

mysql localhost {
  host = TEMPLATE_DB_HOST
  dbname = TEMPLATE_DB_NAME
  user = TEMPLATE_DB_USER
  password = TEMPLATE_DB_PASS
}

##
## Dictionary server settings
##

#dict {
#}

# Most of the actual configuration gets included below. The filenames are
# first sorted by their ASCII value and parsed in that order. The 00-prefixes
# in filenames are intended to make it easier to understand the ordering.
!include conf.d/*.conf

# A config file can also tried to be included without giving an error if
# it's not found:
!include_try local.conf
