## Dovecot configuration file

dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

# Enable installed protocols
protocols = imap lmtp
!include_try /usr/share/dovecot/protocols.d/*.protocol

import_environment PF_DB_USER PF_DB_PASS PF_DB_NAME PF_DB_HOST

mysql localhost {
  user = $ENV:PF_DB_USER
  password = $ENV:PF_DB_PASS
  dbname = $ENV:PF_DB_NAME
  host = $ENV:PF_DB_HOST
}

##
## Dictionary server settings
##

#dict {
#}

# Most of the actual configuration gets included below. The filenames are
# first sorted by their ASCII value and parsed in that order. The 00-prefixes
# in filenames are intended to make it easier to understand the ordering.
!include conf.d/*.conf

# A config file can also tried to be included without giving an error if
# it's not found:
!include_try local.conf
